# This is a basic workflow to help you get started with Actions
name: CI Flutter Android 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - name: flutter build apk for Android
      run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle

    - name: compress zip apk
      run:  zip -r build/app/outputs/flutter-apk
    
    # upload artifact
    - name: Upload android artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: Upload-android-artifact
        path: build/app/outputs/flutter-apk.zip
        if-no-files-found: error
